name: Build and Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install build-essential g++ libgtest-dev

    - name: Generate Makefile and build program
      run: |
        autoreconf --install
        ./configure
        make

    - name: Run unit tests
      run: make check

