name: Build Debian Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install build-essential debhelper

    - name: Generate debian/control
      run: autoreconf --install && ./configure

    - name: Build Debian package
      run: dpkg-buildpackage -us -uc -nc

