name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - branchHTTPserver
      - branchHTTPservMutli

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up QEMU for ARM support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 5. Build and push multi-arch Docker image
      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/http_server:latest

      # 6. Create and push manifest
      - name: Create and Push Manifest
        run: |
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/http_server:latest \
            ${{ secrets.DOCKER_USERNAME }}/http_server:amd64 \
            ${{ secrets.DOCKER_USERNAME }}/http_server:arm64

