name: Build and Push Multi-Arch Docker Image 

on:
  push:
    branches:
      - branchHTTPservMutli
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPservMutli
      - branchHTTPserver
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Встановлюємо QEMU для багатоплатформової збірки
    - name: QEMU install
      uses: docker/setup-qemu-action@v3

    # Налаштовуємо Buildx
    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Створюємо Buildx builder
    - name: Create and use buildx builder
      run: docker buildx create --use --name multiarch-builder

    # Перевіряємо Buildx
    - name: buildx ls
      run: docker buildx ls

    # Логін у Docker Hub
    - name: Log in to Docker Hub
      run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    # Збірка та пуш для amd64
    - name: Build Docker image for amd64
      run: docker buildx build --platform=linux/amd64 -t ${{ vars.DOCKER_USERNAME }}/http_server:amd64 --push .

    # Збірка та пуш для arm64
    - name: Build Docker image for arm64
      run: docker buildx build --platform=linux/arm64 -t ${{ vars.DOCKER_USERNAME }}/http_server:arm64 --push .

    # Створення маніфесту
    - name: Create manifest
      run: docker manifest create ${{ vars.DOCKER_USERNAME }}/http_server:latest \
           --amend ${{ vars.DOCKER_USERNAME }}/http_server:amd64 \
           --amend ${{ vars.DOCKER_USERNAME }}/http_server:arm64

    # Пуш маніфесту
    - name: Push manifest to Docker Hub
      run: docker manifest push ${{ vars.DOCKER_USERNAME }}/http_server:latest

