name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - branchHTTPservMutli
      - branchHTTPserver

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      #  Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up QEMU for ARM support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

            #  Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and push multi-arch Docker image for amd64
      - name: Build and push Docker image for amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/http_server:amd64

      # Build and push multi-arch Docker image for arm64
      - name: Build and push Docker image for arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/http_server:arm64

            # Create manifest for multi-architecture image
      - name: Create manifest for multi-architecture image
        run: |
          manifest-tool push from-args --platforms linux/amd64,linux/arm64 --template-v1 http_server:amd64 --template-v2 ${{ secrets.DOCKER_USERNAME }}/http_server:latest

